//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod check_errors;
pub mod health_check;
pub mod host;
pub mod instance_alerts;
pub mod instance_mail;
pub mod instance_stats;
pub mod mail_verification_tokens;
pub mod last_mail_send;

// has to be re-added on entity regeneration
pub mod state;