//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::check_errors::Entity as CheckErrors;
pub use super::health_check::Entity as HealthCheck;
pub use super::host::Entity as Host;
pub use super::host_overrides::Entity as HostOverrides;
pub use super::instance_stats::Entity as InstanceStats;
pub use super::log::Entity as Log;
