//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::check_errors::Entity as CheckErrors;
pub use super::health_check::Entity as HealthCheck;
pub use super::host::Entity as Host;
pub use super::instance_alerts::Entity as InstanceAlerts;
pub use super::instance_mail::Entity as InstanceMail;
pub use super::instance_stats::Entity as InstanceStats;
pub use super::mail_verification_tokens::Entity as MailVerificationTokens;
